### ISSUE TITLE
大佬，不懂docker.问个问题……

### ISSUE THREAD

**Issue by raintast** [chunfengyao/cloudreve-docker#2]
怎么修改好conf.ini文件再部署到koyeb这种平台直接用😂我有一个postgres的云数据库。

**Comment by chunfengyao** [comment]
cloudreve的config.ini吗？

> raintast

**Comment by chunfengyao** [comment]
在[这一行](https://github.com/chunfengyao/cloudreve-docker/blob/latest/Dockerfile#L34)后面，使用[COPY语句](https://docs.docker.com/engine/reference/builder/#copy)，将自己的config.ini导入进去就行了。

**Comment by chunfengyao** [comment]
或者，可以先开一个docker，然后`docker exec .........`进入容器，修改config.ini。再把容器导出来。

**Comment by chunfengyao** [comment]
或者，可以先开一个docker，然后`docker exec .........`进入容器，修改config.ini。再把容器导出来。

**Comment by raintast** [comment]
> 或者，可以先开一个docker，然后进入容器，修改config.ini。再把容器导出来。`docker exec .........`

**Comment by raintast** [comment]
谢谢大佬……
